#!/bin/bash
set -e
npm install
if [ -d src/index ]; then
  mv src/index .
fi
./gen-index
npm run build
./rm-index
mv index src/ 2>/dev/null || true
node ./mk-package.js > dist/package.json
echo "done."
