#!/bin/bash
set -e

./auto-init

res=$(git status | grep "nothing to commit" | wc -l)
if [ "$res" != 1 ]; then
  echo "Error: unclean working directory, please commit changes first."
  exit 1
fi

if [ $# == 1 ]; then
  t=$1
else
  echo -n "update type `npm version --help | grep -oh \"\\\[.*]\"`: "; read t
fi
./npm_ version "$t"
node ./mk-package.js > dist/package.json
cd dist
npm publish
