#!/bin/bash

./auto-init || exit $?
./fix-dep || exit $?

name="td-tmp"

run_ionic="npm run ionic:serve"
run_horizon="./dev"

hash "tmux" 2>/dev/null
res=$?
set -e

if [ $res == 0 ] && [ "$TMUX" == "" ]; then
  ## use tmux
  tmux start
  tmux new -dP -s ionic "$run_ionic"
  cd "../$name-horizon"
  tmux new -dP -s hz "$run_horizon"
  cd "../$name-ionic"
  tmux attach -t ionic
else
  ## cannot use tmux
  cd "../$name-horizon"
  $run_horizon &
  cd "../$name-ionic"
  $run_ionic
fi
